version: "3"
services:
  genesis:
    build:
      dockerfile: ./dev.Dockerfile
    command:
      - go
      - run
      - ./cmd/tbb
      - run
      - --datadir=/data/.tbb
    volumes:
      - ${HOME}/.tbb:/data/.tbb
      - .:/src

  node:
    build:
      dockerfile: ./dev.Dockerfile
    command:
      - go
      - run
      - ./cmd/tbb
      - run
      - --datadir
      - /tmp/.tbb
      - --bootstraps
      - genesis:8080
    links:
      - genesis
    volumes:
      - .:/src
