version: "3"
services:
  genesis:
    build:
      dockerfile: ./dev.Dockerfile
    command:
      - go
      - run
      - ./cmd/tbb
      - run
      - --datadir=/data/.tbb
      - --advertising-address
      - genesis:8080
      - --miner
      - "q"
    volumes:
      - ${HOME}/.tbb:/data/.tbb
      - .:/src

  node1:
    build:
      dockerfile: ./dev.Dockerfile
    command:
      - go
      - run
      - ./cmd/tbb
      - run
      - --datadir
      - /tmp/.tbb
      - --bootstraps
      - genesis:8080
      - --advertising-address
      - "node1:8080"
      - --miner
      - "hien"
    links:
      - genesis
    volumes:
      - .:/src
  node2:
    build:
      dockerfile: ./dev.Dockerfile
    command:
      - go
      - run
      - ./cmd/tbb
      - run
      - --datadir
      - /tmp/.tbb
      - --bootstraps
      - genesis:8080
      - --advertising-address
      - "node2:8080"
      - --miner
      - "phd"
    links:
      - genesis
    volumes:
      - .:/src
