// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/hienduyph/genesis/database"
	"github.com/hienduyph/genesis/node"
	"github.com/hienduyph/genesis/node/peer"
)

// Injectors from di.go:

func newNode(ctx context.Context, stateConfig *database.StateConfig, peers []peer.PeerNode, advertisingInfo peer.PeerNode) (*node.Node, error) {
	state, err := database.NewState(stateConfig)
	if err != nil {
		return nil, err
	}
	peerState := node.NewPeerState(peers, advertisingInfo, state)
	balanceHandler := node.NewBalanceHandler(state)
	txHandler := node.NewTxHandler(state)
	stateHandler := node.NewStateHandler(state, peers)
	syncHandler := node.NewSyncHandler(state)
	peerHandler := node.NewPeerHandler(peerState)
	nodeNode := node.NewNode(state, peerState, balanceHandler, txHandler, stateHandler, syncHandler, peerHandler)
	return nodeNode, nil
}
