// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"context"
	"github.com/hienduyph/genesis/database"
	"github.com/hienduyph/genesis/node"
	"github.com/hienduyph/genesis/node/handlers"
)

// Injectors from di.go:

func newNode(ctx context.Context, stateConfig *database.StateConfig) (*node.Node, error) {
	state, err := database.NewState(stateConfig)
	if err != nil {
		return nil, err
	}
	balance := handlers.NewBalance(state)
	tx := handlers.NewTx(state)
	nodeNode := node.NewNode(state, balance, tx)
	return nodeNode, nil
}
